### ISSUE TITLE
Losowe oferty jeśli nie ma ofert spełniających kryteria zapytania

### ISSUE THREAD

**Issue by hagmen** [MK-PL/OLX-RSS#12]
W przypadku zapytania które aktualnie nie zwraca żadnej oferty w XML pojawiają się oferty z sekcji znajdującej się poniżej "Sprawdź nasze najnowsze ogłoszenia" . Można to zweryfikować np. na takim zapytaniu https://www.olx.pl/oferty/q-asdasdasdasd/ .

**Comment by MK-PL** [comment]
@hagmen Dziękuję za zgłoszenie. Wprowadziłem poprawkę, proszę o sprawdzenie.

**Comment by hagmen** [comment]
Działa. Szuka tak jak powinien :) Dzięki. A dałbyś radę zrobić coś z tym https://github.com/MK-PL/OLX-RSS/issues/6
