### ISSUE TITLE
Skrypt przestał działać ?

### ISSUE THREAD

**Issue by 69Beyond69** [MK-PL/OLX-RSS#16]
Działa wszystkim skrypt? Bo od 24h kanały nie chcą mi się wczytać

**Comment by 69Beyond69** [comment]
Czy ktoś jeszcze spotkał się z problemem ?

**Comment by hagmen** [comment]
Niestety też mam ten problem. Sądzę, że jest to związane ze zmianami widoku listy ogłoszeń.

**Comment by MK-PL** [comment]
Hejka @69Beyond69 i @hagmen. 
Sprawdźcie proszę repo, czy teraz skrypt ponownie u Was działa.

**Comment by 69Beyond69** [comment]
Wczytany, ale niestety wydaje mi się, że nie działa, brak wyników po wczytaniu kanału :/

**Comment by MK-PL** [comment]
@69Beyond69 możesz podać przykładowy link? Sprawdziłbym.

**Comment by 69Beyond69** [comment]
http://fauxtales69.cba.pl//OLX_(Official)/src/get.php?url=https%3A%2F%2Fwww.olx.pl%2Fd%2Felektronika%2Ffotografia%2Fq-Nikon-D300%2F

**Comment by MK-PL** [comment]
@69Beyond69 u mnie lokalnie działa po podaniu urla do OLX:
![image](https://user-images.githubusercontent.com/8502239/174307535-9ceea8fb-4846-479f-89fb-48e035e94f9d.png)

Sprawdź, czy na pewno masz aktualną wersję skryptu.

**Comment by 69Beyond69** [comment]
Ok, działa, prawdopodobnie pozmieniało mi znaki na małe podczas wgrywania skryptu na serwer za pierwszym razem :D Wielkie dzięki. A przy okazji wiesz może jakie są limity zapytań na minutę na OLX ?

**Comment by MK-PL** [comment]
@69Beyond69 Super 💪 
Odnośnie zapytań, to nie mam takich informacji.
