### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function find() on boolean in

### ISSUE THREAD

**Issue by pniewiadowski** [MK-PL/OLX-RSS#3]
Cześć,

dostaje poniższy komunikat po dodaniu linku:

`Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/html/OLX-RSS/src/simple_html_dom.php on line 76

Warning: file_get_contents(): Failed to enable crypto in /var/www/html/OLX-RSS/src/simple_html_dom.php on line 76

Warning: file_get_contents(https://www.olx.pl/nieruchomosci/mieszkania/sprzedaz/bydgoszcz): failed to open stream: operation failed in /var/www/html/OLX-RSS/src/simple_html_dom.php on line 76

Fatal error: Uncaught Error: Call to a member function find() on boolean in /var/www/html/OLX-RSS/src/get.php:41 Stack trace: #0 {main} thrown in /var/www/html/OLX-RSS/src/get.php on line 41`

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie. 

Z opisu błędu wynika, że problem dotyczy certyfikatu OpenSSL na serwerze z PHP.
Można znaleźć w Google rozwiązania tego problemu, wpisując 'SSL operation failed with code 1'.

Jedno z proponowanych rozwiązań, to zmiana wersji PHP na nowszą. U mnie lokalnie jest zainstalowana wersja 7.2.7 i link prawidłowo zwraca kanał RSS.

**Comment by pniewiadowski** [comment]
Dzięki za pomoc. To pomogło.
