### ISSUE TITLE
Błąd przy generowaniu linku rss

### ISSUE THREAD

**Issue by saytin** [MK-PL/OLX-RSS#4]
Kilkaset błędów 
Warning: preg_match(): Compilation failed: invalid range in character class at offset 4 in /srv/http/OLX-RSS/src/simple_html_dom.php on line 1385

I na koniec

Warning: preg_match_all(): Compilation failed: invalid range in character class at offset 4 in /srv/http/OLX-RSS/src/simple_html_dom.php on line 690

Warning: Invalid argument supplied for foreach() in /srv/http/OLX-RSS/src/simple_html_dom.php on line 697

Warning: preg_match_all(): Compilation failed: invalid range in character class at offset 4 in /srv/http/OLX-RSS/src/simple_html_dom.php on line 690

Warning: Invalid argument supplied for foreach() in /srv/http/OLX-RSS/src/simple_html_dom.php on line 697
https://www.olx.pl/elektronika/komputery/komputery-stacjonarne/ OLX RSS pl

PHP 7.3.1 (cli) (built: Jan 11 2019 07:28:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies

w logu apache jest to samo.

**Comment by MK-PL** [comment]
Witaj @saytin,
U mnie ten URL zadziałał, więc sprawdziłem dokładniej i okazało się, że używany w OLX-RSS skrypt `PHP Simple HTML DOM Parser` był w starszej wersji, która nie działała poprawnie na PHP 7.3. Zaktualizowałem ten skrypt do najnowszej wersji w OLX-RSS https://github.com/MK-PL/OLX-RSS/commit/c54c3d70f535b8a1889b02c5df5aff0c708cf889. Powinno to teraz działać na PHP 7.3. 

https://github.com/sunra/php-simple-html-dom-parser/issues/64
https://sourceforge.net/projects/simplehtmldom/files/simplehtmldom/1.8.1/

**Comment by saytin** [comment]
działa. Dzięki.
