### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found

### ISSUE THREAD

**Issue by damianos56** [MK-PL/OLX-RSS#5]
Witam,
Po kliknięciu generuj zwraca następujący komunikat.

Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/OLX-RSS/src/SimpleXMLElement.php:7 Stack trace: #0 /var/www/html/OLX-RSS/src/get.php(13): include() #1 {main} thrown in /var/www/html/OLX-RSS/src/SimpleXMLElement.php on line 7

Proszę o poradę jak rozwiązać problem.
Sprawdzane na PHP 7.3.4

**Comment by MK-PL** [comment]
Witaj @damianos56,
Prawdopodobnie brakuje pakietu od obsługi `xml` na Twoim serwerze PHP. Taką informację odnalazłem po wpisaniu frazy `Class 'SimpleXMLElement' not found` w wyszukiwarce. W każdym razie możesz albo doinstalować ten pakiet albo go aktywować w konfiguracji, jeśli już jest zainstalowany - szczegóły są w  linkach poniżej:

https://stackoverflow.com/a/35834836
https://stackoverflow.com/a/50470937
https://www.php.net/manual/en/dom.setup.php
