### ISSUE TITLE
Błędne przekierowania dla ofert z Otomoto 

### ISSUE THREAD

**Issue by hagmen** [MK-PL/OLX-RSS#6]
Posiadam na OLX takie [wyszukiwanie](https://www.olx.pl/motoryzacja/samochody/volvo/s80/?search%5Bfilter_float_price%3Ato%5D=25000&search%5Bfilter_enum_model%5D%5B0%5D=s80&search%5Bfilter_float_year%3Afrom%5D=2003&search%5Bfilter_enum_petrol%5D%5B0%5D=lpg&search%5Bfilter_enum_transmission%5D%5B0%5D=automatic) . W przypadku jeśli oferta pochodzi z OLX i pojawi się w czytniku RSS to po kliknięciu na nią poprawnie przekierowuje do ogłoszenia. Natomiast jeśli ogłoszenie jest z Otomoto to po kliknięciu na odnośnik z RSS jestem przekierowany na stronę z takim [wyszukiwaniem](https://www.olx.pl/motoryzacja/samochody/volvo/s80/?search%5Bfilter_float_price%3Ato%5D=25000&amp;search%5Bfilter_enum_model%5D%5B0%5D=s80&amp;search%5Bfilter_float_year%3Afrom%5D=2003&amp;search%5Bfilter_enum_petrol%5D%5B0%5D=petrol&amp;search%5Bfilter_enum_transmission%5D%5B0%5D=automatic) 

Problem dotyczy zarówno wyszukiwań związanych z samochodami jak i z częściami do samochodów. Czy jest możliwość poprawienia tego?

**Comment by MK-PL** [comment]
Wprowadziłem poprawkę, która naprawia linki do serwisu OtoMoto na kanale RSS.
Proszę sprawdzić: [link](https://github.com/MK-PL/OLX-RSS/releases/tag/v0.1.5)

**Comment by hagmen** [comment]
Wielkie dzięki. Działa tak jak powinno.
