### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by JuniorJPDJ** [MK-PL/OLX-RSS#8]
Cześć,
Stworzyłem docker-compose do twojego projektu:
https://github.com/JuniorJPDJ/OLX-RSS-compose
Bardzo ułatwia instalacje.
Jeżeli chciałbyś o tym wspomnieć w swoim README, to byłoby fajnie ;)

**Comment by d33tah** [comment]
@JuniorJPDJ w sumie czemu po prostu nie zrobisz pull requesta? ;)

**Comment by JuniorJPDJ** [comment]
Bo compose trzymam osobno, dockerfile trzymam w jednym miejscu z usługą ;)
