### ISSUE TITLE
Nie generuje RSS (pojawia się kilka mylących linków)

### ISSUE THREAD

**Issue by dgomp** [MK-PL/OLX-RSS#9]
Witam, zaimportowałem pliki do mojego ftp, który ma PHP 5.6. Następnie wszedłem na stronę i wygenerowałem RSS „HTTPS://WWW.OLX.PL/OFERTY/Q-POODLE/”. Klikając Generuj, witryna podała załącznik zwrotny. Co może być nie tak?
![xml result](https://user-images.githubusercontent.com/52968011/61304030-e0e15780-a7be-11e9-84a3-d107b5083300.png)

**Comment by JuniorJPDJ** [comment]
ten problem wynika z #7 
RSS jest generowany, ale przegladarka probuje wyswietlic jego XML jako HTML

**Comment by dgomp** [comment]
Czy ktoś wie, jak go rozwiązać?

**Comment by JuniorJPDJ** [comment]
Poprawilem to tutaj: https://github.com/JuniorJPDJ/OLX-RSS

**Comment by MK-PL** [comment]
@JuniorJPDJ Dziękuję, zrobiłem merge'a z Twojego pull requesta.
